# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    default_locale:            "%locale%"
    adapter_cache_dir:         "%kernel.root_dir%/cache/%kernel.environment%/filesystem"
    adapter_tmp_files:         "%kernel.root_dir%/../TempFiles"
    adapter_files:             "%kernel.root_dir%/../Files"
    mail_from:                 "do-not-reply@alluco.com"
    mail_from_name:            "Alluco.com"
    mailtos:
        - { name: 'Wafa Bouatay', email: 'rmr@demconstruct.com' }
#        - { name: 'Alluco Info', email: 'info@alluco.com' }

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }

    twig.extension.i18n:
       class: Twig_Extensions_Extension_I18n
       tags:
           - { name: twig.extension }

    twig.extension.array:
       class: Twig_Extensions_Extension_Array
       tags:
           - { name: twig.extension }

    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }

    bcc.twig.extension:
        class: BCC\ExtraToolsBundle\Twig\TwigExtension
        tags:
            -  { name: twig.extension }
