_security_logout:
    pattern:  /logout

_security_login:
    pattern:  /login
    defaults: { _controller: "AllucoSecurityBundle:Security:login" }

_security_check:
    pattern:  /login_check
    requirements:
        _method:  POST

_security_register:
    pattern:  /register
    defaults: { _controller: "AllucoSecurityBundle:Security:register" }

_security_lost_password:
    pattern:  /lostPassword
    defaults: { _controller: "AllucoSecurityBundle:Security:lostPassword" }

_security_lost_genpassword:
    pattern:  /genNewPassword/{id}/{code}
    defaults: { _controller: "AllucoSecurityBundle:Security:genNewPassword" }

_security_profile:
    pattern:  /myProfile
    defaults: { _controller: "AllucoSecurityBundle:Profile:myProfile" }
    requirements:
        _method:  GET

_security_profile_post:
    pattern:  /myProfile
    defaults: { _controller: "AllucoSecurityBundle:Profile:myProfilePost" }
    requirements:
        _method:  POST


_security_profile_avatar:
    pattern:  /myAvatar
    defaults: { _controller: "AllucoSecurityBundle:Profile:myAvatar" }