<?php

namespace Alluco\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CertifTransRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertifTransRepository extends EntityRepository
{
}
