<?php

namespace Alluco\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductpicTransRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductpicTransRepository extends EntityRepository
{
}
