<?php

namespace Alluco\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductTransRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductTransRepository extends EntityRepository
{
}
