<?php

namespace Alluco\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StaticpageTransRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaticpageTransRepository extends EntityRepository
{
}
